author:       "kevinh24"
name:         "KevinHeryanto"
title:        "OS222: Operating Systems 2022-2"
githublink:   "https://github.com/kevinh24/os222"
myloglink:    "/TXT/mylog.txt"
tarballlink:  "https://os.vlsm.org/Log/kevinh24.tar.bz2.txt"
encoding:     UTF-8
markdown:     kramdown
input:        GFM
hard_wrap:    false
github:       [metadata]